#!/usr/bin/env bash

function usage {
	echo "$0 connect|disconnect|reconnect|stats|log [1-6]";
	exit 0;
}

function ensure_config {
	# Check for the config, first in file, followed by environment.  Fail if we can't find it.
	if [[ ! -f ~/.vpnconfig.ovpn ]]
	then
		if [[ ! -z "${OPENVPN_CONFIG}" ]]
		then 
			echo 'Storing $OPENVPN_CONFIG in ~/.vpnconfig.ovpn...';
    		echo "${OPENVPN_CONFIG}" > ~/.vpnconfig.ovpn;
    	else
    		echo 'Missing OpenVPN config.  Place it in ~/.vpnconfig.ovpn or set $OPENVPN_CONFIG environment variable';
    		exit 1;
    	fi
	fi

	# If we're not root, the following commands will need sudo
	SUDOCMD="";
	[[ $(id -u) != "0" ]] && SUDOCMD="sudo ";

	# Check for dbus-daemon
	ps -ef | grep 'dbus-daemon' | grep -v grep &>/dev/null;
	if [[ $? -ne 0 ]]
	then
		echo "Starting dbus-daemon...";
		[[ -e /run/dbus/pid ]] && ${SUDOCMD}rm -f /run/dbus/pid;
		${SUDOCMD}/usr/bin/dbus-daemon --system;
	fi

	ps -ef | grep 'openvpn3-service-netcfg' | grep -v grep &>/dev/null;
	if [[ $? -ne 0 ]]
	then
		echo "Starting openvpn3-service-netcfg...";
		${SUDOCMD}nohup /usr/lib/x86_64-linux-gnu/openvpn3-linux/openvpn3-service-netcfg &>/dev/null &
	fi
}

[[ $# -lt 1 ]] && usage;

case $1 in
	connect )
		ensure_config;
		openvpn3 session-start -c ~/.vpnconfig.ovpn;
		;;
	disconnect )
		ensure_config;
		openvpn3 session-manage --disconnect -c ~/.vpnconfig.ovpn;
		;;
	reconnect )
		ensure_config;
		openvpn3 session-manage --reconnect -c ~/.vpnconfig.ovpn;
		;;
	stats )
		ensure_config;
		openvpn3 session-stats -c ~/.vpnconfig.ovpn;
		;;
	log )
		ensure_config;
		LOGLEVELARG=""
		if [[ $# -gt 1 ]]
		then
			LOGLEVELARG="--log-level ${2}"
		fi
		openvpn3 log ${LOGLEVELARG} -c ~/.vpnconfig.ovpn;
		;;
	*)
	  usage;;
esac
